name: Playwright Cucumber Tests

on:
 push:
   branches: [ main, master ]
 pull_request:
   branches: [ main, master ]
 workflow_dispatch:
  inputs:
   browser:
     description: 'Select browser'
     required: true
     default: 'chromium'
     type: choice
     options:
       - chromium
       - edge
       - firefox
       - webkit
   executionMode:
     description: 'Execution Mode'
     required: true
     default: 'sequential'
     type: choice
     options:
       - sequential
       - parallel
   environment:
     description: 'Select environment'
     required: true
     default: 'qa'
     type: choice
     options:
       - qa
       - uat
       - prod

jobs:
 test:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout source code
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '22'

     - name: Install dependencies
       run: npm ci

     - name: Install Playwright browsers
       run: npx playwright install --with-deps

     - name: Run Cucumber tests
       run: |
        if [ "${{ github.event.inputs.executionMode }}" = "parallel" ]; then
          npx cross-env TEST_ENV=${{ github.event.inputs.environment || 'qa' }} BROWSER=${{ github.event.inputs.browser || 'chromium' }} npm test -- --parallel 3
        else
          npx cross-env TEST_ENV=${{ github.event.inputs.environment || 'qa' }} BROWSER=${{ github.event.inputs.browser || 'chromium' }} npm test
        fi

     - name: Generate HTML report
       if: always()
       run: npx cross-env TEST_ENV=${{ github.event.inputs.environment || 'qa' }} BROWSER=${{ github.event.inputs.browser || 'chromium' }} npm run report

     - name: Upload HTML report
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: cucumber-html-report
         path: reports/html-report
